### PR TITLE
[WIP] Minor README enhancement: External links for libraries

### PR DESCRIPTION
**Pull request by hangtwenty**
## What

Making some of the mentions of external libs link to their sites/readmes.

## Why

Helps newbs who might be introduce to these things via lore.

----

## More?

If you like the gist of this, I'd be happy to go through for lots of other mentions and make them into links. (Of course not all READMEs need this treatment... I thought to do it here since `lore` has the admirable goal of making things more accessible to diverse audiences.)

Let me know?

### CODE REVIEW

**Comment by montanalow** [comment]
Thanks for the links! Do you want me to merge this as is, or do you want to tag with WIP until you're ready to merge?

**Comment by hangtwenty** [comment]
@montanalow If this is good now feel free to merge, but since you like the idea I'll do more either way 😉

**Comment by montanalow** [comment]
@hangtwenty I started work on a sphinx documentation project in `/docs`, that I won't be able to really flush out for a couple more weeks. It'd be a huge help if you're interested in contributing to the project documentation by organizing a table of contents so that the major modules/classes are auto-documented using their comments.

**Comment by hangtwenty** [comment]
@montanalow Great, I would love to help with that. Today/tomorrow are busy but I'll get started later this week!

**Pull request merged**
